version: "2.4"
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  flyway:
    build:
      context: ./
    command: -url=jdbc:mysql://mariadb -schemas=myschema -user=root -password=password -connectRetries=60 migrate
    depends_on:
      - mariadb

